GET http://127.0.0.1:8080/




###
POST http://127.0.0.1:8080/add/
Content-Type: application/json

{
  "cocktail_name": "White Russian",
  "description": "A decadent adult milkshake",
  "glass": "short glass",
  "garnish": null,
  "ingredients": [
    {
      "name": "vodka",
      "amount": "2", 
      "unit": "part"
    },
    {
    "name": "kalua",
    "amount": "1", 
    "unit": "part"
    },
    {
    "name": "whole milk",
    "amount": "2", 
    "unit": "part"
    }
  ],
  "directions": [
    {
      "step": 1,
      "instruction": "Fill an old fashioned (short) glass with ice"
    },
    {
      "step": 2,
      "instruction": "Pour over the vodka and kalua"
    },
    {
      "step": 3,
      "instruction": "Top with whole milk"
    }
  ]
}