GET http://127.0.0.1:8080/list/

### Home Page
GET http://127.0.0.1:8080/


### White Russian
POST http://127.0.0.1:8080/add/
Content-Type: application/json

{
  "cocktail_name": "White Russian",
  "description": "The dude abides.",
  "glass": "short glass",
  "image_url": "whiterussian.jpg",
  "garnish": null,
  "ingredients": [
    {
      "name": "vodka",
      "amount": 2, 
      "unit": "part"
    },
    {
    "name": "kalua",
    "amount": 1, 
    "unit": "part"
    },
    {
    "name": "whole milk",
    "amount": 2, 
    "unit": "part"
    }
  ],
  "directions": [
    {
      "step": 1,
      "instruction": "Fill an old fashioned (short) glass with ice"
    },
    {
      "step": 2,
      "instruction": "Pour over the vodka and kalua"
    },
    {
      "step": 3,
      "instruction": "Top with whole milk"
    }
  ]
}

### Mint Julep

POST http://127.0.0.1:8080/add/
Content-Type: application/json

{
  "cocktail_name": "Mint Julep",
  "description": "Signature drink of the Kentucky Derby.",
  "glass": "Julep or rocks",
  "image_url": "mintjulep.jpg",
  "garnish": "bitters, mint sprig",
  "ingredients": [
    {
      "name": "simple syrup",
      "amount": 0.25, 
      "unit": "ounce"
    },
    {
    "name": "mint leaves",
    "amount": 8, 
    "unit": "leaves"
    },
    {
    "name": "bourbon",
    "amount": 2, 
    "unit": "ounce"
    }
  ],
  "directions": [
    {
      "step": 1,
      "instruction": "In a Julep cup or rocks glass, lightly muddle the mint and syrup."
    },
    {
      "step": 2,
      "instruction": "Add the bourbon and pack tightly with crushed ice."
    },
    {
      "step": 3,
      "instruction": "Stir until the cup is frosted on the outside."
    }, 
    {
      "step": 4,
      "instruction": "Top with more crushed ice to form an ice dome and garnish with a mint sprig and few optional drops of bitters."
    }
  ]
}

### Dry Martini

POST http://127.0.0.1:8080/add/
Content-Type: application/json

{
  "cocktail_name": "Dry Martini",
  "description": "Prefered beverage of 007.",
  "glass": "martini glass",
  "image_url": "drymartini.jpg",
  "garnish": "olive or lemon twist",
  "ingredients": [
    {
      "name": "cracked ice",
      "amount": 2, 
      "unit": "large cubes"
    },
    {
    "name": "London dry gin",
    "amount": 2.5, 
    "unit": "ounce"
    },
    {
    "name": "dry vermouth",
    "amount": 0.5, 
    "unit": "ounce"
    }
  ],
  "directions": [
    {
      "step": 1,
      "instruction": "In mixing glass or cocktail shaker filled with ice, combine gin and vermouth."
    },
    {
      "step": 2,
      "instruction": "Stir well, about 30 seconds, then strain into martini glass."
    },
    {
      "step": 3,
      "instruction": "Garnish with olive or lemon twist and serve."
    }
  ]
}

### Mojito

POST http://127.0.0.1:8080/add/
Content-Type: application/json

{
  "cocktail_name": "Mojito",
  "description": "A refreshing beverage with mint and rum.",
  "glass": "highball",
  "garnish": "mint sprig",
  "image_url": "mojito.jpg",
  "ingredients": [
    {
      "name": "white rum",
      "amount": 2, 
      "unit": "oz"
    },
    {
    "name": "mint leaves",
    "amount": 3, 
    "unit": "count"
    },
    {
    "name": "fresh lime juice",
    "amount": 0.75, 
    "unit": "oz"
    },
    {
    "name": "simple syrup",
    "amount": 0.5, 
    "unit": "oz"
    },
    {
    "name": "club sode",
    "amount": 2, 
    "unit": "oz"
    }
  ],
  "directions": [
    {
      "step": 1,
      "instruction": "Lightly muddle the mint in a shaker."
    },
    {
      "step": 2,
      "instruction": "Add the rum, lime juice, simple syrup and ice and give it a brief shake."
    },
    {
      "step": 3,
      "instruction": "Strain into a highball glass over fresh ice."
    },
    {
      "step": 4,
      "instruction": "Top with the club soda."
    },
    {
      "step": 5,
      "instruction": "Garnish with mint sprig"
    }
  ]
}
